module.exports = {
    UsuarioDTO : require('./usuario.dto'),
    MultimediaDTO : require('./multimedia.dto'),
    RegistroModuloDTO : require('./registromodulo.dto'),
    AtencionDTO : require('./atencion.dto'),
    PrioridadDTO : require('./prioridad.dto'),
    FranjahorariaDto : require('./franjahoraria.dto'),
    TicketDTO : require('./ticket.dto'),
    CasuisticaDto : require('./casuistica.dto'),
    SubcasuisticaDTO : require('./subcasuistica.dto'),
    TipoModuloDTO : require('./tipomodulo.dto'),
    StdregistroDTO : require('./stdregistro.dto'),
    TiempoGestionDTO : require('./tiempogestion.dto'),
    ModuloDTO : require('./modulo.dto'),
    StdatencionDto : require('./stdatencion.dto'),
};